# Generated by Django 4.2.6 on 2023-12-04 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
