# Generated by Django 4.2.6 on 2023-11-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_pet_listing_id_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='application_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='shelter_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
