# Generated by Django 4.2.6 on 2023-11-12 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_application_id_notification_shelter_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='pet_listing_id',
        ),
    ]
