# Generated by Django 4.2.6 on 2023-12-08 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_age'),
        ('comments', '0002_alter_comment_options'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='application_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='associated_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='shelter_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.application'),
        ),
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.comment'),
        ),
    ]
