# Generated by Django 4.2.6 on 2023-12-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notification_application_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='associated_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
