# Generated by Django 4.2.6 on 2023-11-11 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('petlistings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('NA', 'NA')], default='NA', max_length=10)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('shelter_name', models.CharField(blank=True, max_length=150)),
                ('occupation', models.CharField(blank=True, max_length=150)),
                ('salary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('existing_pets', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3+', '3 or more')], default='0', max_length=10)),
                ('home_yard', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10)),
                ('safe_guard', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10)),
                ('message', models.TextField(blank=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_as_applicant', to=settings.AUTH_USER_MODEL)),
                ('pet_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petlistings.petlisting')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_as_shelter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
