# Generated by Django 4.2.6 on 2023-12-04 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StrayAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('status', models.CharField(choices=[('lost', 'Lost'), ('spotted', 'Spotted'), ('rescued', 'Rescued')], max_length=20)),
                ('animal', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('fish', 'Fish'), ('unknown', 'Unknown')], max_length=20)),
                ('breed', models.CharField(choices=[('corgi', 'Corgi'), ('labrador', 'Labrador'), ('retriever', 'Retriever'), ('german shepherd', 'German Shepherd'), ('pussycat', 'Pussycat'), ('unknown', 'Unknown')], max_length=20)),
                ('description', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
