# Generated by Django 4.2.6 on 2023-12-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strayanimals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strayanimal',
            name='breed',
            field=models.CharField(choices=[('corgi', 'Corgi'), ('labrador', 'Labrador'), ('retriever', 'Retriever'), ('german shepherd', 'German Shepherd'), ('pussycat', 'Pussycat'), ('unknown', 'Unknown'), ('persian', 'Persian'), ('shorthair', 'Shorthair'), ('sphynx', 'Sphynx'), ('parakeet', 'Parakeet'), ('chicken', 'Chicken')], max_length=20),
        ),
    ]
