# Generated by Django 4.2.6 on 2023-12-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strayanimals', '0002_alter_strayanimal_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strayanimal',
            name='animal',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('unknown', 'Unknown')], max_length=20),
        ),
    ]
