version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: backend/petpal/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/petpal:/app
    restart: always
    networks:
      - my-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    restart: always
    networks:
      - my-network

networks:
  my-network:


