version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: backend/petpal/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/petpal:/app


  frontend:
    build: ./frontend
    container_name: frontend

    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
