version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: backend/petpal/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/petpal:/app


  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
