# Generated by Django 4.2.6 on 2023-12-04 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pethubuser',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pethubuser',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
