# Generated by Django 4.2.6 on 2023-12-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pethubuser_lat_pethubuser_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='pethubuser',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pethubuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
