# Generated by Django 4.2.6 on 2023-11-26 21:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('petlistings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petlisting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
