# Generated by Django 4.2.6 on 2023-11-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petlistings', '0002_petlisting_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petlisting',
            name='colour',
            field=models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('brown', 'Brown'), ('sable', 'Sable')], max_length=20),
        ),
    ]
