# Generated by Django 4.2.6 on 2023-12-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petlistings', '0003_alter_petlisting_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petlisting',
            name='animal',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('fish', 'Fish'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='petlisting',
            name='breed',
            field=models.CharField(choices=[('corgi', 'Corgi'), ('labrador', 'Labrador'), ('retriever', 'Retriever'), ('german shepherd', 'German Shepherd'), ('pussycat', 'Pussycat'), ('persian', 'Persian'), ('shorthair', 'Shorthair'), ('sphynx', 'Sphynx'), ('parakeet', 'Parakeet'), ('chicken', 'Chicken'), ('shorthair', 'Bass'), ('goldfish', 'Goldfish'), ('other', 'Other')], max_length=20),
        ),
    ]
