# Generated by Django 4.2.6 on 2023-12-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petlistings', '0004_alter_petlisting_animal_alter_petlisting_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petlisting',
            name='breed',
            field=models.CharField(choices=[('corgi', 'Corgi'), ('labrador', 'Labrador'), ('retriever', 'Retriever'), ('german shepherd', 'German Shepherd'), ('pussycat', 'Pussycat'), ('persian', 'Persian'), ('shorthair', 'Shorthair'), ('sphynx', 'Sphynx'), ('parakeet', 'Parakeet'), ('chicken', 'Chicken'), ('bass', 'Bass'), ('goldfish', 'Goldfish'), ('other', 'Other')], max_length=20),
        ),
    ]
