# Generated by Django 4.2.6 on 2023-12-08 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petlistings', '0005_alter_petlisting_breed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petlisting',
            name='address',
        ),
        migrations.RemoveField(
            model_name='petlisting',
            name='province',
        ),
    ]
